DROP TABLE IF EXISTS PendingPassword CASCADE;
DROP TABLE IF EXISTS ActivityTag CASCADE;
DROP TABLE IF EXISTS Tag CASCADE;
DROP TABLE IF EXISTS Authority CASCADE;
DROP TABLE IF EXISTS Followers CASCADE;
DROP TABLE IF EXISTS GroupPerson CASCADE;
ALTER TABLE Person DROP FOREIGN KEY fk_curr_act;
DROP TABLE IF EXISTS Activity CASCADE;
DROP TABLE IF EXISTS Person CASCADE;
DROP TABLE IF EXISTS Groups CASCADE;

